language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests/
